name: Release For Production Dora Metrics
concurrency: production

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  dora-release:
    name: Echo Github Release Tag
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Extract GitHub Tag Name
        id: extract_tag
        run: |
          GITHUB_TAG=${GITHUB_REF#refs/tags/}
          echo "Extracted Tag: $GITHUB_TAG"
